imports:
    - { resource: ./config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            channels: ['!app_access']
            action_level: error
            handler: nested
            excluded_404s:
                - ^/
        app_access:
            type: stream
            channels: ['app_access']
            path: '%kernel.logs_dir%/%kernel.environment%-access.log'
            level: info
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
