#!/bin/sh

set -e

branch=$(echo $GIT_BRANCH | cut -d/ -f 2)
echo $JOB_NAME:$branch $WORKSPACE

rm -rf SRPMS

echo "Stopping existing Container..."
docker stop registry.ci.rmp.api.bbci.co.uk/programmes-docker-base || true

echo "Running CI in container..."
docker run --rm -u `id -u`:`id -g` -e OAUTH="$OAUTH_TOKEN" -v "$WORKSPACE":/mnt/ registry.ci.rmp.api.bbci.co.uk/programmes-docker-base script/ci-docker

if [ "$BUILD_TYPE" = "pull-request" ]
then
    echo "Running mbt..."
	BUILD_COMMAND="mbt"
else
    echo "Running cosmos-build..."
	BUILD_COMMAND="cosmos-build"
fi

$BUILD_COMMAND -s docker -i registry.ci.rmp.api.bbci.co.uk/programmes-docker-base \
--static-assets=$STATIC_ASSETS \
--static-assets-bucket=$STATIC_ASSETS_BUCKET \
--static-assets-bucket-region=$STATIC_ASSETS_BUCKET_REGION \
--static-assets-bucket-role-arn=$STATIC_ASSETS_BUCKET_ROLE_ARN




# Upload local RPMs to a repository named cosmos-<component>
echo 'running COSMOS-RELEASE....'
os=`cosmos-release guess-os RPMS/*.el6*.rpm`
echo "RPM operating system:  $os"
echo `pwd`

source=`cosmos-release describe-checkout . git git@github.com:bbc/programmes-frontend.git 04af7536569a7285c8dd47b02128181a67e7ec71`
echo "-- SOURCE:  $source --------"


echo "Stopping container..."
docker stop registry.ci.rmp.api.bbci.co.uk/programmes-docker-base || true
