#!/bin/sh

set -e

branch=$(echo $GIT_BRANCH | cut -d/ -f 2)
echo $JOB_NAME:$branch $WORKSPACE

rm -rf SRPMS

echo "Stopping existing Container..."
docker stop registry.ci.rmp.api.bbci.co.uk/programmes-docker-base || true

echo "Running CI in container..."
docker run --rm -u `id -u`:`id -g` -e OAUTH="$OAUTH_TOKEN" -v "$WORKSPACE":/mnt/ registry.ci.rmp.api.bbci.co.uk/programmes-docker-base script/ci-docker

echo 'running COSMOS-RELEASE....'

os=`cosmos-release guess-os RPMS/*.el6*.rpm`
source=`cosmos-release describe-checkout`
version=`cosmos-release generate-version programmes-frontend`

mbt -s docker -i registry.ci.rmp.api.bbci.co.uk/programmes-docker-base --rpmversion $version
cosmos-release service programmes-frontend RPMS/*.rpm --release-version $version --os $os


cosmos-release publish-assets \
--role $STATIC_ASSETS_BUCKET_ROLE_ARN \
$STATIC_ASSETS \
"$STATIC_ASSETS_BUCKET/programmes-frontend"

echo "Stopping container..."
docker stop registry.ci.rmp.api.bbci.co.uk/programmes-docker-base || true
